# Generated by Django 5.0 on 2026-09-13 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_review_reported'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reported',
        ),
    ]
